export const columns = [
    {name: 'MARQUE', uid: 'marque'},
    {name: 'MODELE', uid: 'model'},
    {name: 'MATRICULE', uid: 'matricule'},
    {name: 'YEAR', uid: 'year'},
    {name: 'KILOMETRES', uid: 'kilometers'},
    {name: 'COLOR', uid: 'color'},
    {name: 'TYPE', uid: 'type'},
    {name: 'COST', uid: 'cost'},
    {name: 'STATUS', uid: 'status'},
    {name: 'ACTIONS', uid: 'actions'},
];
export const users = [
    {
        id: 1,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'open'
    },
    {
        id: 2,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'open'
    },
    {
        id: 3,
        name: 'Jane Fisher',
        role: 'Senior Developer',
        team: 'Development',
        status: 'open',
        age: '22',
        avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
        email: 'jane.fisher@example.com',
    },
    {
        id: 4,
        name: 'William Howard',
        role: 'Community Manager',
        team: 'Marketing',
        status: 'maintenance',
        age: '28',
        avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
        email: 'william.howard@example.com',
    },
    {
        id: 5,
        name: 'Kristen Copper',
        role: 'Sales Manager',
        team: 'Sales',
        status: 'open',
        age: '24',
        avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
        email: 'kristen.cooper@example.com',
    },
    {
        id: 6,
        name: 'Tony Reichert',
        role: 'CEO',
        team: 'Management',
        status: 'open',
        age: '29',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        email: 'tony.reichert@example.com',
    },
    {
        id: 10,
        name: 'Kristen Copper',
        role: 'Sales Manager',
        team: 'Sales',
        status: 'open',
        age: '24',
        avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
        email: 'kristen.cooper@example.com',
    },
    {
        id: 8,
        name: 'Jane Fisher',
        role: 'Senior Developer',
        team: 'Development',
        status: 'open',
        age: '22',
        avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
        email: 'jane.fisher@example.com',
    },
    {
        id: 7,
        name: 'Zoey Lang',
        role: 'Technical Lead',
        team: 'Development',
        status: 'closed',
        age: '25',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
        email: 'zoey.lang@example.com',
    },

    {
        id: 9,
        name: 'William Howard',
        role: 'Community Manager',
        team: 'Marketing',
        status: 'maintenance',
        age: '28',
        avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
        email: 'william.howard@example.com',
    },
];
