export const columns = [
    {name: 'MARQUE', uid: 'marque'},
    {name: 'MODELS', uid: 'model'},
    {name: 'MATRICULE', uid: 'matricule'},
    {name: 'YEAR', uid: 'year'},
    {name: 'KILOMETERS', uid: 'kilometers'},
    {name: 'COLOR', uid: 'color'},
    {name: 'TYPE', uid: 'type'},
    {name: 'COST', uid: 'cost'},
    {name: 'STATUS', uid: 'status'},
    {name: 'ACTIONS', uid: 'actions'},
];
export const users = [
    {
        id: 1,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'open'
    },
    {
        id: 2,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'open'
    },
    {
        id: 3,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '12500056',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'open'
    },
    {
        id: 4,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'open'
    },
    {
        id: 5,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'open'
    },
    {
        id: 6,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'open'
    },
    {
        id: 7,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'open'
    },
    {
        id: 8,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'open'
    },
    {
        id: 7,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'closed'
    },

    {
        id: 9,
        marque: 'Peugeot Renault',
        model: '208',
        matricule: 'AO24547',
        year: '2012',
        kilometers: '0',
        color: 'Rouge',
        type : 'Camping',
        cost: '29000 DT',
        status : 'closed'
    },
];
